-- AlterTable
ALTER TABLE "collection_of_models" ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "employeeid" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "email" SET DATA TYPE VARCHAR(100);
